title: Moonwalk
author: Abhinav Saxena
url: https://www.abhinavsaxena.com/moonwalk # サイトのルートアドレス
description: > # サイトの説明（複数行可）
  Moonwalk is a fast and elegant Jekyll theme with a clean dark mode. It comes with horizontal list (for navbar and footer), card list (for portfolio), and a generic vertical list. It is very easy to modify in case you want to build over it - please see _layouts/home.html to do that.

permalink: /:slug

favicon: "./logo.png" # サイトのファビコンへの相対パス

twitter:
    username: abhinav # 必要に応じて更新または削除
    card: summary_large_image

#theme: moonwalk # GitHub Pagesを使う場合はremote_theme: abhinavs/moonwalkに変更
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # "light"、"dark"、"auto"から選択可能
  appearance_toggle: true # ユーザーが外観を切り替えられるか
  back_home_text: "home.." # 投稿レイアウトのホームページリンクのテキストをカスタマイズ
  date_format: "%Y-%m-%d" # 日付の表示形式をカスタマイズ
  show_description: true # ブログの説明を表示
  show_navbar: true # 水平ナビゲーションバーを表示
  show_footer: true # ホームページのフッターリンクを表示、_data/home.ymlで追加
  show_copyright: true # フッターに著作権表示を追加
  # 以下のキーはホームレイアウトの表示制御用
  show_projects: true # プロジェクトをカードで表示、_data/home.ymlで追加
  show_blog: true # _postsに追加されたブログ投稿を表示
  show_old_projects: true # 古いプロジェクトをカードで表示、_data/home.ymlで追加
  show_misc_list: false # その他の詳細を縦リストで表示、_data/home.ymlで追加
  show_reading_time: true # ブログ投稿の単語数と読了時間を表示
  show_tags: true # ブログ投稿にタグを表示
  # "home"ページ用のオプション
  home:
    title_projects: Portfolio
    title_misc_list: Details
    title_blog: Blog
    title_old_projects: Old Projects

soopr:
  publish_token: "" # https://www.soopr.co でサインアップしてトークンを取得し、シェアやリアクションをカスタマイズ

highlighter: rouge # コードハイライト用

sass:
  style: :compressed # CSS圧縮設定

plugins:
  - jekyll-feed # RSSフィード生成
  - jekyll-seo-tag # SEOタグ生成
